name: Shell Commands #name of the entire workflow

#Events that will trigger the workflow
on: [push]

#Jobs are defined using the job key

jobs:
  # Job number 1
  run-shell-command:
    runs-on: ubuntu-latest #specifies the OS on the VM(virtual machine)
    steps:
      # action 1
      - name: echo a string #bash command for Ubuntu and Linux, powershell commands for Windows
        run: echo "Hello World"
        # action 2
      - name: multiline script
        run: |
          node -v
          npm -v
      # action 3
      - name: python Command
        run: |
          import platform
          print(platform.processor())
        shell: python #specifies the type of command

  # Job number2
  run-windows-commands:
    runs-on: windows-latest
    steps:
      - name: Directory Powershell
        run: Get-Location
        # this job will run on bash command
      - name: Directory Bash
        run: pwd
        shell: bash
